### ISSUE TITLE
Deno Upgrade broke my apps

### ISSUE THREAD

**Issue by nhrones** [deno-windowing/dwm#13]
Upgraded to Deno 1.30.0 and now my apps fail with 
```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'ops')
const DECODED = Deno.build.os === "windows" && Deno.build.arch === "x86_64" 
? Deno.core.ops.op_base64_decode(BASE64) : new Uint8Array();

            ^
    at https://glfw-binaries.deno.dev/3.4.0/glfw3_windows.js:2:89
```

**Comment by nhrones** [comment]
I downloaded a fresh repo of dwm, and tried the examples! Same error!
```
\C:\Users\nhron\dev\GitHub\dwm> cd examples
\C:\Users\nhron\dev\GitHub\dwm\examples> deno run -A --unstable canvas.ts
error: Uncaught TypeError: Cannot read properties of undefined (reading 'ops')
const DECODED = Deno.build.os === "windows" && Deno.build.arch === "x86_64" ? Deno.core.ops.op_base64_decode(BASE64) : new Uint8Array();
                                                                                        ^      
    at https://glfw-binaries.deno.dev/3.4.0/glfw3_windows.js:2:89
\C:\Users\nhron\dev\GitHub\dwm\examples> 
```

**Comment by load1n9** [comment]
upgrade off of canary, we're fixing this issue should have this issue fixed asap

**Comment by nhrones** [comment]
Not on canary!  I upgraded to the not current version Deno V1.30.0

**Comment by load1n9** [comment]
will update asap

**Comment by DjDeveloperr** [comment]
It's blocked on new release of Skia Canvas. Will update it and cut DWM release as soon as possible.

**Comment by DjDeveloperr** [comment]
New releases are out:

- DWM: v0.3.0
- Skia Canvas: v0.5.1

Both should work on Deno v1.30.0.
